version: '3.8'
services:
  xsshunter-go:
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./db/:/app/db/
      - ./screenshots/:/app/screenshots/
    ports:
      - "1449:1449"
    env_file:
      - .env