version: '3'
services:
  xsshunter-go:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/:/app/db/
      - ./screenshots/:/app/screenshots/
      - ./src:/app/src # For development
    ports:
      - "1449:1449"
    env_file:
      - .env