version: '3'
services:
  xsshunter-go:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/:/app/db/
      - ./screenshots/:/app/screenshots/
    ports:
      - "1449:1449"
    environment:
      - GO_ENV=development
    env_file:
      - .env