version: '3'
services:
  xsshunter-go:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/:/app/db/
      - ./screenshots/:/app/screenshots/
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development