services:
  xsshunter-go:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      # - ./db/:/app/db/
      # - ./screenshots/:/app/screenshots/
      # - ./src:/app/src # For development
      - ./:/app
    ports:
      - "1449:1449"
    environment:
      - DATABASE_URL=postgres://xsshunter:xsshunter@postgres:5432/xsshunter?sslmode=disable
    env_file:
      - .env
    networks:
      - xsshunter-go
    depends_on:
      - postgres
      - redis
  postgres:
      image: postgres:16.2-alpine3.19
      environment:
          POSTGRES_USER: xsshunter
          POSTGRES_PASSWORD: xsshunter
          POSTGRES_DB: xsshunter
      volumes:
          - ./postgres_db/:/var/lib/postgresql/data/
      ports:
          - "5432:5432"
      networks:
        - xsshunter-go
  redis:
      image: redis:7.2.4-alpine3.19
      volumes:
          - ./redis:/data
      ports:
          - "6379:6379"
      networks:
        - xsshunter-go

networks:
  xsshunter-go:
    driver: bridge