services:
  xsshunter-go:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      # - ./db/:/app/db/
      # - ./screenshots/:/app/screenshots/
      # - ./src:/app/src # For development
        - ./:/app
    ports:
      - "1449:1449"
    env_file:
      - .env