version: '3'
services:
  xsshunter-go:
    image: adamjsturge/xsshunter-go:main
    volumes:
      - ./db/:/app/db/
      - ./screenshots/:/app/screenshots/
    ports:
      - "1449:1449"
    environment:
      - CONTROL_PANEL_ENABLED=true